# Generated by Django 2.2.1 on 2019-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
