# Generated by Django 2.2.1 on 2019-06-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='seller_messages',
            new_name='seller_message',
        ),
    ]
