# Generated by Django 2.2.1 on 2019-06-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='subscribed',
            new_name='subscribe',
        ),
    ]
