# Generated by Django 2.2.1 on 2019-06-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20190609_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='subscribe',
            new_name='subscribed',
        ),
    ]
