# Generated by Django 2.2.1 on 2019-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20190609_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingpreference',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
