# Generated by Django 2.2.1 on 2019-06-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_marketingpreference_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='update',
            new_name='updated',
        ),
    ]
