# Generated by Django 2.2.1 on 2019-06-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
